### ISSUE TITLE
Eclipse could not show revision information for files which are moved from one folder(java package) to another folder

### ISSUE THREAD

**Issue by humphreygao** [eclipse-platform/eclipse.platform.team#24]
quick diff:

![image](https://user-images.githubusercontent.com/52394598/173501689-cb472fd3-f823-4539-a56b-691ad2c5287c.png)

All lines are recongized as Additions

**Comment by vogella** [comment]
Which version control system are you using? If that is Git, please report to the EGit project https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EGit
