### ISSUE TITLE
BatchingLock checking out with CVS

### ISSUE THREAD

**Issue by ewillink** [eclipse-platform/eclipse.platform.team#29]
Using the 2020-12 version of CVS cvlient on 2022-12, attempting to check out with CVS gives a popup

An internal error occurred during: "Checking out 'lpg.test' from CVS".
'void org.eclipse.team.internal.core.subscribers.BatchingLock$ThreadInfo.<init>(org.eclipse.team.internal.core.subscribers.BatchingLock, org.eclipse.team.internal.core.subscribers.BatchingLock$IFlushOperation)'

and error log

java.lang.NoSuchMethodError: 'void org.eclipse.team.internal.core.subscribers.BatchingLock$ThreadInfo.<init>(org.eclipse.team.internal.core.subscribers.BatchingLock, org.eclipse.team.internal.core.subscribers.BatchingLock$IFlushOperation)'
	at org.eclipse.team.internal.ccvs.core.syncinfo.ReentrantLock$CVSThreadInfo.<init>(ReentrantLock.java:43)
	at org.eclipse.team.internal.ccvs.core.syncinfo.ReentrantLock.createThreadInfo(ReentrantLock.java:67)
	at org.eclipse.team.internal.core.subscribers.BatchingLock.acquire(BatchingLock.java:269)
	at org.eclipse.team.internal.ccvs.core.resources.EclipseSynchronizer.beginBatching(EclipseSynchronizer.java:494)
	at org.eclipse.team.internal.ccvs.core.resources.EclipseSynchronizer.run(EclipseSynchronizer.java:1465)
	at org.eclipse.team.internal.ccvs.ui.operations.CheckoutProjectOperation.checkout(CheckoutProjectOperation.java:173)
	at org.eclipse.team.internal.ccvs.ui.operations.CheckoutMultipleProjectsOperation.checkout(CheckoutMultipleProjectsOperation.java:60)
	at org.eclipse.team.internal.ccvs.ui.operations.CheckoutOperation.checkout(CheckoutOperation.java:47)
	at org.eclipse.team.internal.ccvs.ui.operations.CheckoutOperation.execute(CheckoutOperation.java:33)
	at org.eclipse.team.internal.ccvs.ui.operations.CVSOperation.run(CVSOperation.java:77)
	at org.eclipse.team.internal.ui.actions.JobRunnableContext.run(JobRunnableContext.java:155)
	at org.eclipse.team.internal.ui.actions.JobRunnableContext$ResourceJob.runInWorkspace(JobRunnableContext.java:83)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Since the CVS client is no longer updated, the old API neds to be preserved.,

**Comment by ewillink** [comment]
Blocks https://bugs.eclipse.org/bugs/show_bug.cgi?id=581278

**Comment by mickaelistria** [comment]
> Since the CVS client is no longer updated, the old API neds to be preserved.,

That's not how things work here. Platform doesn't commit to support of deprecated unmaintained extensions that have relied on internal code.
Here is a reminder of the announcement regarding CVS support removal in Platform: https://www.eclipse.org/lists/cross-project-issues-dev/msg18643.html . You'll see the best path forward if you care about CVS is either to step in Platform with clear commitment to revive and maintain it as part of Platform; or to create a fork of it. A fork is IMO better.

> Blocks https://bugs.eclipse.org/bugs/show_bug.cgi?id=581278

Having a CVS client in Eclipse IDE doesn't seem to be an actual requirement for this bug as far as I understand.

**Comment by iloveeclipse** [comment]
I assume simple recompilation of CVS bundles should be sufficient to fix this concrete issue.
Regression is coming most likely from this commit that changed `ThreadInfo` inner class to static one: https://github.com/eclipse-platform/eclipse.platform.team/commit/ff7f0d838fb6cd3a7091dd3365d0ae3d2417b69b

**Comment by mickaelistria** [comment]
I'm closing this one as Platform won't do much here, beyond encouraging voluntary people in forking older CVS support.

**Comment by ewillink** [comment]
As commented on cross-project-dev

The CVS deprecation was announced in September 2021. It announced removal of the ongoing distribution, not refactoring and breakage.

My understanding of the disciplined deprecation was that two major releases were required after an announcement, but since e6 is impossibly distant the platform has taken to breakage in minor versions. Nonetheless I would expect two releases on the yearly cadence so breakage within 18 months seems very wrong and to merit a regression fix.

A 'simple recompilation' is perhaps not that hard.

**Comment by laeubi** [comment]
Expectations are always high and contributions are always low compared to that. Especially this major/minor discussion is simply hilarious, do you think anyone would have jumped in to upgrade CVS (I would assume that most new contributors never has used it including me so why bother?) if platform would have released a "major" instead of a "minor" version increment? Still there would be the same situation as of today.

`ThreadInfo` is even an internal class so it could change even for micro or whatever version increments without a notice.

**Comment by ewillink** [comment]
Yes. A genuinely, rather than artificially, internal ThreadInfo can certainly change so long as all the side effects are resolved by all SimRel contributors.

Breaking CVS without a reasonable deprecation transition is an external side effect that has not been so resolved.

**Comment by iloveeclipse** [comment]
Once again: complaining alone will not bring anyone forward.

If someone wants CVS support on latest platform: please contribute. E. g. even *early* testing of nightly builds would help to identify and fix the problem.

Assuming ff7f0d8 is the only "breaking" change in platform for CVS, one simple possibility would be to revert this commit (which has no real significant value anyway, compared with broken CVS).

**Comment by ewillink** [comment]
In this case it appears that the failure would have been detected by compiling the sources.
