### ISSUE TITLE
Extracted CVS Client 'beta'

### ISSUE THREAD

**Issue by JAndrassy** [eclipse-platform/eclipse.platform.team#30]
I modified a copy of this repository (from 4.23 branch) to build the CVS Client and I made quick fixes for 4.28.
The repository is here https://github.com/JAndrassy/org.eclipse.team.cvs
There are build jars in the Release section to test the plugin as a drop-in. (Only for Eclipse versions starting from 2023-03)

**Comment by mickaelistria** [comment]
Hi, thanks for working on it. I would recommend you to create an entry on Eclipse Marketplace for it, this is the best way to increase visibility to the right audience.
I'm closing this issue as there is nothing to be done on this particular repo.
