### ISSUE TITLE
Retire CVS from master

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.team#8]
No one stepped up to maintain CVS after we stopped delivering it. Lets remove it from master. 

@akurtakov ok for you?

**Comment by vogella** [comment]
Would be nice to remove it before https://github.com/eclipse-platform/eclipse.platform/issues/7

**Comment by akurtakov** [comment]
Go for it. No matter the other issue it's good to be done.

**Comment by vogella** [comment]
Nice to see you getting even more aggressive with deletions. :-)

**Comment by merks** [comment]
Actually people did complain.

https://www.eclipse.org/forums/index.php/t/1110398/

**Comment by vogella** [comment]
> Actually people did complain.
> 
> https://www.eclipse.org/forums/index.php/t/1110398/

Sorry, misphrased. I changed the comment to: No one stepped up to maintain CVS after we stopped delivering it. Lets remove it from master.

**Comment by ghost** [comment]
Another strategy could be to move CVS to its own repository and move that repository to 'the attic'/archive. At least code would be easier to find for anybody that is looking for it and create a for if they like to continue work.

Kind of opposite to merging everything in one big repository, tough having it standalone could have benefits to a very limited set of users.

**Comment by laeubi** [comment]
> Another strategy could be to move CVS to its own repository and move that repository to 'the attic'/archive. At least code would be easier to find for anybody that is looking for it and create a for if they like to continue work.

@rolfth just take the required actions for this, I think no one will complain... you can even just fork it to an own organization/repo just now.

**Comment by akurtakov** [comment]
@rolfth This is exactly what we proposed https://www.eclipse.org/lists/cross-project-issues-dev/msg18643.html but no one cared enough to do so.

**Comment by iloveeclipse** [comment]
@vogella : could you please update https://www.eclipse.org/eclipse/platform-cvs/ to mention that the project is now stopped and the sources can be found at ... or just remove the page?

**Comment by vogella** [comment]
@iloveeclipse sorry, still in vacation, please delete yourself. GH is the new truth so deleting is the best imho

**Comment by iloveeclipse** [comment]
> [rg/eclipse/platform-cvs/](https://www.eclipse.org/eclipse/platform-cvs/)

I assume I have no rights to do so.

**Comment by akurtakov** [comment]
Website is in git but it's overall in tragic state . https://github.com/eclipse-platform/www.eclipse.org-eclipse/tree/master/platform-cvs is where one should do the changes.
